// so much for production level images =]]
const chatThemes = [
  {
    name: "Default",
    backgroundImage: "none",
    themeColor: "#559157",
    lColor: "#123",
    emoji: "👍",
  },
  {
    name: "Dark",
    backgroundImage: "none",
    background: "#1f1e1c",
    mBackground: "#111",
    themeColor: "#111",
    secondaryColor: "#fff",
    reactedByBackGround: "#111",
    reactionBackground: "#111",
    contrastingColor: "#fff",
    reactedByBorder: "1px solid #fff",
    emoji: "🤡",
    class: "clicky",
    mContainer: "btnLike",
  },
  {
    name: "Glowing in darkness",
    backgroundImage: "none",
    background: "#1f1e1c",
    mBackground: "#111",
    themeColor:
      "linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000)",
    secondaryColor: "#fff",
    emoji: "😈",
    class: "glow",
  },
  {
    name: "Mysterious",
    backgroundImage:
      "https://www.desktopbackground.org/p/2015/04/29/940436_paintings-hippie-lsd-stoned_1000x792_h.jpg",
    themeColor: `rgb(255, ${Math.random() * 255}, 178)`,
    secondaryColor: "#fff",
    backgroundSize: "contain",
    emoji: "👽",
  },
  {
    name: "Trump",
    backgroundImage: "none",
    themeColor: "#FF6700",
    secondaryColor: "#fff",
    mBackground: "#FF6700",

    class: "clicky",
    emoji: "🌕",
    mContainer: "btnLike",
  },
  {
    name: "SnowyDay",
    backgroundImage: "none",
    themeColor: "lightskyblue",
    mBackground: "lightskyblue",
    secondaryColor: "#035fad",
    emoji: "❄️",
  },
  {
    name: "Gay",
    backgroundImage: "https://wallpaper.dog/large/10697297.jpg",
    themeColor: "#6f42c1",
    secondaryColor: "#f4c7ff",
    emoji: "💖",
  },
  {
    name: "Hot",
    backgroundImage:
      "https://p4.wallpaperbetter.com/wallpaper/810/214/386/surreal-abstract-drugs-lsd-wallpaper-preview.jpg",
    themeColor: "#dc3545",
    secondaryColor: "#b32d00",
    backgroundColor: "",
    emoji: "🔥",
  },
  {
    name: "KillMe",
    backgroundImage: "none",
    themeColor: "#198754",
    secondaryColor: "#20c997",
    emoji: "👻",
  },
  {
    name: "Romantic",
    backgroundImage: "none",
    themeColor: "lightPink",
    secondaryColor: "#fff",

    mBackground: "#ffb7d5",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    emoji: "💗",
  },
  {
    name: "Hehe",
    backgroundImage: "none",
    themeColor:
      "linear-gradient(rgb(255, 143, 178) 0%, rgb(167, 151, 255) 50%,rgb(0, 229, 255) 100%)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    gradient: true,
    class: "hehe",
    emoji: "💥",
  },
  {
    name: "Insta",
    backgroundImage: "none",
    themeColor: "linear-gradient(to right, #fcb045, #fd1d1d, #833ab4)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem Bradley Hand, cookie",
    lFont: "900 10px Bradley Hand, cookie",
    reactedByBackGround: "linear-gradient(to right, #fcb045, #fd1d1d, #833ab4)",
    reactionBackground: "#111",
    contrastingColor: "#fff",
    gradient: true,
    class: "insta",
    emoji: "📷",
  },
  {
    name: "Atlas",
    backgroundImage: "none",
    themeColor: "linear-gradient(to right, #4bc0c8, #c779d0, #feac5e)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    gradient: true,
    class: "atlas",
    emoji: "🖤",
  },
  {
    name: "Twitch",
    backgroundImage: "none",
    themeColor: "linear-gradient(to left, #2a0845, #6441a5)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    gradient: true,
    class: "twitch",
    emoji: "🎃",
  },
  {
    name: "Hornymoon",
    backgroundImage: "none",
    themeColor: "linear-gradient(to left, #00223e, #ffa17f)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    gradient: true,
    class: "hornymoon",
    emoji: "🌕",
  },
  {
    name: "NeonFreak",
    backgroundImage: "none",
    themeColor: "linear-gradient(to left, #0b8793, #360033)",
    secondaryColor: "#fff",
    mBackground: "#111",
    msFont: "400 1rem cookie, cursive",
    lFont: "900 10px cookie, cursive",
    gradient: true,
    class: "neonfreak",
    emoji: "✨",
  },
  {
    name: "Birthday",
    backgroundImage: "none",
    background: "#1f1e1c",
    mBackground: "#111",
    themeColor: "#111",
    secondaryColor: "#fff",
    reactedByBackGround: "#111",
    reactionBackground: "#111",
    contrastingColor: "#fff",
    reactedByBorder: "1px solid #fff",
    emoji: "🤡",
    class: "clicky",
    mContainer: "btnLike",
  },
];
export default chatThemes;
